import type { NextPage } from 'next'
import { useTheme } from 'next-themes'
import Head from 'next/head'

const Home: NextPage = () => {
  const { theme, setTheme } = useTheme()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-white dark:bg-black">
        <div className="flex flex-col items-center justify-center py-20">
          <h1 className="text-5xl font-bold text-center text-gray-800 dark:text-gray-100">
            Next Themes + Tailwind Dark Mode
          </h1>

          <button
            className="px-4 py-2 mt-16 font-semibold text-white bg-black rounded-md dark:text-black dark:bg-white"
            onClick={() => {
              setTheme(theme === 'light' ? 'dark' : 'light')
            }}
          >
            Change Theme
          </button>
        </div>
      </div>
    </>
  )
}

export default Home
