/* eslint-disable @next/next/no-img-element */
import type { NextPage } from 'next'
import Head from 'next/head'
import { AccordionMaker } from '../components'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/** Two sections */}
      <main className="md:flex">
        {/** Section one */}
        <div className='px-2 md:w-[50%] md:flex flex-col items-center justify-center'>
          <AccordionMaker Header="Search for a job" body="Hea" />
          <AccordionMaker Header="Find a person you know" body="Hea" />
          <AccordionMaker Header="Learn a new skill" body="Hea" />
        </div>
        {/** Section one ends*/}

        {/** Section two */}
        <div className='flex items-center justify-center p-2 h-[400px] md:h-[full] md:w-[50%]'>
          <img src="/images/book-reading.jpeg" alt="Person reading a book" loading='lazy' className='h-full'/>
        </div>
        {/** Section two ends*/}
      </main>
    </>
  )
}

export default Home
